services:
    mongodb:
        image: mongo:8.0.10 
        container_name: benchmark-mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
